easyops-cn/next-advanced-bricks

- bricks/nav/src/launchpad-config/MenuGroup.tsx
- bricks/nav/src/launchpad-config/index.spec.tsx
- bricks/nav/src/launchpad-config/index.tsx
- bricks/nav/src/launchpad-config/interfaces.ts
- bricks/nav/src/launchpad-config/styles.shadow.css
> feat(): support config blacklist

- bricks/nav/src/launchpad-config/MenuGroup.tsx
- bricks/nav/src/launchpad-config/index.spec.tsx
- bricks/nav/src/launchpad-config/index.tsx
- bricks/nav/src/launchpad-config/interfaces.ts
> fix(): ignore blocked items for launchpad config

- bricks/advanced/docs/eo-next-table.md
- bricks/advanced/src/next-table/host-context.css
- bricks/advanced/src/next-table/styles.shadow.css
> fix(): refine table row height

- bricks/advanced/build.config.js
- bricks/advanced/src/pdf-viewer/index.tsx
> fix(): no js entries in dist root

- bricks/advanced/src/next-table/Table.tsx
> fix(): fix table drag

- bricks/diagram/src/draw-canvas/EdgeComponent.tsx
SVG masks seem to have perf issues
请勾选以下两组选项其中之一：
或者：
>
>
> perf(): use clip-path instead of mask

- bricks/visual-builder/src/raw-data-preview/index.tsx
- bricks/visual-builder/src/shared/compat_internals.ts
> fix(): make a v2/v3 compatible secret internals

- bricks/diagram/src/draw-canvas/CellComponent.tsx
- bricks/diagram/src/draw-canvas/EdgeComponent.tsx
- bricks/diagram/src/draw-canvas/EditingLineComponent.tsx
- bricks/diagram/src/draw-canvas/HoverStateContext.ts
- bricks/diagram/src/draw-canvas/LineConnectorComponent.tsx
- bricks/diagram/src/draw-canvas/LineEditorComponent.tsx
- bricks/diagram/src/draw-canvas/index.tsx
- bricks/diagram/src/draw-canvas/interfaces.ts
- bricks/diagram/src/draw-canvas/processors/handleMouseDown.spec.ts
- bricks/diagram/src/draw-canvas/processors/handleMouseDown.ts
- bricks/diagram/src/editable-label/styles.shadow.css
- bricks/diagram/src/shared/canvas/styles.shadow.css
Closes CMDB_VIEW-314
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 拓扑图支持快捷键shift快速选择和取消选择多个元素，原框选功能需要支持选中边

- bricks/form/build.config.js
- bricks/form/src/auto-complete/index.tsx
- bricks/form/src/bootstrap.ts
- bricks/form/src/input.ts
- bricks/form/src/input/index.tsx
- bricks/form/src/search/index.tsx
> fix(): merge bricks

- bricks/nav/src/launchpad-config/index.tsx
> fix(): fix an issue that custom items in dir not blockable

- bricks/form/src/input.ts
> fix(): wrapLocalBrick requires import order

- bricks/form/src/select/index.tsx
Closes CD-8999
请勾选以下两组选项其中之一：
或者：
>
>
> fix(select): enable flip of sl-popup

- bricks/form/src/date-picker/styles.shadow.css
Refs BRICK-563 BRICK-561
请勾选以下两组选项其中之一：
或者：
>
>
> fix(date-picker): update custom styles

- bricks/vs/src/code-editor/index.css
- bricks/vs/src/code-editor/index.tsx
> fix(): fix style, avoid conflicts with v2 vs editor

- bricks/visual-builder/src/pre-generated-config/convertToBrickConf.ts
> fix(): covert children to slots

- bricks/diagram/src/draw-canvas/NodeComponent.tsx
> fix(): workaround for firefox bug of foreign object overflow visible not working

- bricks/visual-builder/src/data-providers/get-config-by-data-for-ai.ts
> fix(): do not use attr as query for relation existence

- bricks/vs/src/code-editor/index.tsx
> fix(): set fixedOverflowWidgets defaults to true

- bricks/form-platform/src/user-or-user-group-select/index.tsx
- bricks/form/src/auto-complete/index.tsx
- bricks/form/src/checkbox/index.tsx
- bricks/form/src/date-picker/index.tsx
- bricks/form/src/dynamic-form-item/index.tsx
- bricks/form/src/form-item/index.tsx
- bricks/form/src/general-switch/index.tsx
- bricks/form/src/icon-select/index.tsx
- bricks/form/src/input/index.tsx
- bricks/form/src/radio/index.tsx
- bricks/form/src/select/index.tsx
- bricks/form/src/submit-buttons/index.tsx
- bricks/form/src/textarea/index.tsx
- bricks/form/src/time-picker/index.tsx
- bricks/form/src/time-range-picker/index.tsx
- bricks/form/src/upload/upload-file/index.tsx
- bricks/form/src/upload/upload-image/index.tsx
- bricks/markdown/src/markdown-editor/index.tsx
- shared/form/package.json
- shared/form/src/index.ts
- shared/form/src/interfaces.ts
- shared/form/src/pickFormItemProps.ts
> fix(): pick form item props

- bricks/diagram/src/display-canvas/index.spec.tsx
- bricks/diagram/src/draw-canvas/CellComponent.tsx
- bricks/diagram/src/draw-canvas/NodeComponent.tsx
- bricks/diagram/src/draw-canvas/index.spec.tsx
- bricks/diagram/src/draw-canvas/index.tsx
- bricks/diagram/src/shared/canvas/processors/getEditingLinePoints.spec.ts
- bricks/diagram/src/shared/canvas/processors/getEditingLinePoints.ts
- bricks/diagram/src/shared/canvas/useEditableLineMap.ts
- bricks/diagram/src/shared/canvas/useLineMarkers.ts
> fix(): use position instead of transform to fix perf issues on clients without GPU

- bricks/diagram/src/shared/canvas/styles.shadow.css
Refs CMDB_CONSUME-829
请勾选以下两组选项其中之一：
或者：
>
>
> style(): 调整容器背景色

- bricks/form/src/textarea/index.spec.tsx
- bricks/form/src/textarea/index.tsx
- bricks/mini-chart/src/mini-line-chart/index.tsx
- bricks/vs/src/code-editor/index.tsx
> fix(): fix resize entry in old Firefox

- bricks/vs/.gitignore
- bricks/vs/package.json
- bricks/vs/scripts/pre-build.js
- bricks/vs/src/code-editor/index.spec.tsx
- bricks/vs/src/code-editor/index.tsx
- bricks/vs/src/code-editor/workers/spellCheck.spec.ts
- bricks/vs/src/code-editor/workers/spellCheck.ts
- bricks/vs/src/code-editor/workers/spellCheck.worker.ts
- bricks/vs/src/code-editor/workers/spellCheckRemoteWorker.ts
- bricks/vs/src/code-editor/workers/yamlLinter.ts
- bricks/vs/test.config.js
- declarations/global.d.ts
- yarn.lock
> feat(code-editor): add spell check

- shared/spell-check/package.json
- shared/spell-check/src/spellCheck.ts
> fix(): compatible with legacy node.js

- bricks/diagram/src/draw-canvas/NodeComponent.tsx
> fix(): fix node position when node re-render

- bricks/diagram/src/draw-canvas/decorators/DecoratorLine.tsx
- bricks/diagram/src/draw-canvas/index.tsx
> fix(): fix moving decorator lines

- bricks/diagram/docs/eo-draw-canvas.md
- bricks/diagram/src/draw-canvas/CellComponent.tsx
- bricks/diagram/src/draw-canvas/decorators/DecoratorArea.tsx
- bricks/diagram/src/draw-canvas/decorators/DecoratorContainer.tsx
- bricks/diagram/src/draw-canvas/decorators/DecoratorRect.tsx
- bricks/diagram/src/draw-canvas/decorators/DecoratorText.tsx
- bricks/diagram/src/draw-canvas/index.spec.tsx
- bricks/diagram/src/draw-canvas/index.tsx
- bricks/diagram/src/draw-canvas/interfaces.ts
- bricks/diagram/src/shared/canvas/styles.shadow.css
> feat(): support set decorator style

- bricks/ai/src/chat-view/ChatService.ts
- bricks/ai/src/chat-view/hooks/useChatViewInfo.ts
- bricks/ai/src/chat-view/index.tsx
> feat(): support set config and form data

- bricks/diagram/src/draw-canvas/index.tsx
> fix(): use memoized line markers when moving cells other than decorator lines

- bricks/diagram/docs/eo-draw-canvas.md
- bricks/diagram/src/draw-canvas/CellComponent.tsx
- bricks/diagram/src/draw-canvas/LockIcon.tsx
- bricks/diagram/src/draw-canvas/NodeComponent.tsx
- bricks/diagram/src/draw-canvas/decorators/DecoratorArea.tsx
- bricks/diagram/src/draw-canvas/decorators/DecoratorContainer.tsx
- bricks/diagram/src/draw-canvas/decorators/DecoratorLine.tsx
- bricks/diagram/src/draw-canvas/decorators/DecoratorRect.tsx
- bricks/diagram/src/draw-canvas/decorators/DecoratorText.tsx
- bricks/diagram/src/draw-canvas/decorators/index.tsx
- bricks/diagram/src/draw-canvas/index.spec.tsx
- bricks/diagram/src/draw-canvas/index.tsx
- bricks/diagram/src/draw-canvas/interfaces.ts
- bricks/diagram/src/draw-canvas/processors/getContentEditable.ts
- bricks/diagram/src/draw-canvas/processors/getLineLockIconPosition.spec.ts
- bricks/diagram/src/draw-canvas/processors/getLineLockIconPosition.ts
- bricks/diagram/src/draw-canvas/processors/handleKeyboard.ts
- bricks/diagram/src/draw-canvas/processors/handleMouseDown.ts
- bricks/diagram/src/draw-canvas/processors/handleNodeContainedChange.ts
- bricks/diagram/src/draw-canvas/processors/isLocked.ts
- bricks/diagram/src/draw-canvas/processors/toggleLock.spec.ts
- bricks/diagram/src/draw-canvas/processors/toggleLock.ts
- bricks/diagram/src/shared/canvas/styles.shadow.css
> feat(eo-draw-canvas): support lock cells

- bricks/diagram/src/draw-canvas/index.spec.tsx
- bricks/diagram/src/draw-canvas/index.tsx
> feat(): draw-canvas添加canvas.contextmenu事件用于实现右键粘贴节点功能 ref CUSTOMIZE-1091

- bricks/diagram/src/draw-canvas/CellComponent.tsx
- bricks/diagram/src/draw-canvas/index.spec.tsx
- bricks/diagram/src/draw-canvas/index.tsx
> fix(): stop context menu event propagation from cell

- bricks/diagram/docs/eo-draw-canvas.md
- bricks/diagram/src/draw-canvas/CellComponent.tsx
- bricks/diagram/src/draw-canvas/index.spec.tsx
- bricks/diagram/src/draw-canvas/interfaces.ts
> feat(): event 'cell.contextmenu' supports multiple targets

- bricks/form/src/color-picker/styles.shadow.css
Refs CMDB_CONSUME-912
请勾选以下两组选项其中之一：
或者：
>
>
> style(): color-picker 展示居中

- bricks/form/src/color-picker/styles.shadow.css
Refs CMDB_CONSUME-912
请勾选以下两组选项其中之一：
或者：
>
>
> style(): color-picker 去掉上下边距

- bricks/form/src/color-picker/styles.shadow.css
Refs CMDB_CONSUME-912
请勾选以下两组选项其中之一：
或者：
>
>
> style(): color-picker 设置文本最少宽度

- bricks/presentational/docs/eo-card-item.md
- bricks/presentational/src/card-item/index.tsx
- bricks/presentational/src/card-item/styles.shadow.css
Refs MONITOR_SETTING-570
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support title sufix slot

- bricks/v2-adapter/src/data-providers/load-bricks.tsx
> fix(): support some legacy transform functions

- bricks/advanced/src/workbench-layout-v2/index.spec.tsx
- bricks/advanced/src/workbench-layout-v2/index.tsx
Closes DESKTOP-470
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 支持工作台样式与布局配置

- bricks/diagram/src/display-canvas/index.tsx
Refs CMDB_VIEW-391
请勾选以下两组选项其中之一：
或者：
>
>
> chore(eo-display-canvas): activeTarget支持高亮效果

- bricks/form/docs/eo-select.md
- bricks/form/src/interface.ts
- bricks/form/src/select/index.shadow.css
- bricks/form/src/select/index.spec.ts
- bricks/form/src/select/index.tsx
Closes CMDB_DISCOVERY-1252
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): eo-select 支持下来候选项支持展示caption

- bricks/form/src/select/index.tsx
Closes CMDB_DISCOVERY-1252
请勾选以下两组选项其中之一：
或者：
>
>
> style(): eo-select 支持dropdownStyle设置下拉样式

- bricks/advanced/src/interfaces/workbench.ts
- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.tsx
- bricks/advanced/src/workbench-layout-v2/index.spec.tsx
- bricks/advanced/src/workbench-layout-v2/index.tsx
refs: DESKTOP-508
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 调整layouts数据结构

- bricks/advanced/src/workbench-layout-v2/index.tsx
refs: DESKTOP-508
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复点击保存 layouts 数据丢失的问题

- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.module.css
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.tsx
- bricks/ai-portal/src/cruise-canvas/constants.ts
- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/interfaces.ts
- bricks/ai-portal/src/cruise-canvas/reducers/jobs.ts
- bricks/ai-portal/src/cruise-canvas/styles.module.css
- bricks/ai-portal/src/cruise-canvas/useLayout.ts
> fix(): fix auto scroll, collapse tool output

- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.module.css
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.tsx
- bricks/ai-portal/src/cruise-canvas/ZoomBar/ZoomBar.module.css
- bricks/ai-portal/src/cruise-canvas/bricks.ts
- bricks/ai-portal/src/cruise-canvas/i18n.ts
- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/reducers/task.ts
- bricks/ai-portal/src/cruise-canvas/styles.module.css
- bricks/ai-portal/src/cruise-canvas/useTaskDetail.ts
- mocks.mjs
> fix(): refine style

- bricks/advanced/src/workbench-layout-v2/index.spec.tsx
- bricks/advanced/src/workbench-layout-v2/index.tsx
- bricks/advanced/src/workbench-layout-v2/utils.spec.ts
- bricks/advanced/src/workbench-layout-v2/utils.ts
refs:DESKTOP-513
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复删除卡片失败和适配默认布局数据

- bricks/ai-portal/docs/cruise-canvas.md
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.module.css
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.tsx
- bricks/ai-portal/src/cruise-canvas/i18n.ts
- bricks/ai-portal/src/cruise-canvas/interfaces.ts
- bricks/ai-portal/src/cruise-canvas/reducers/jobs.ts
> fix(): refine tool call

- bricks/advanced/src/workbench-layout-v2/DraggableComponentMenuItem.module.css
- bricks/advanced/src/workbench-layout-v2/DraggableComponentMenuItem.tsx
- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.spec.tsx
- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.tsx
- bricks/advanced/src/workbench-layout-v2/index.spec.tsx
- bricks/advanced/src/workbench-layout-v2/index.tsx
refs: DESKTOP-512
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): ui 优化

- bricks/ai-portal/src/cruise-canvas/NodeInstruction/NodeInstruction.module.css
- bricks/ai-portal/src/cruise-canvas/NodeInstruction/NodeInstruction.tsx
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.module.css
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.tsx
- bricks/ai-portal/src/cruise-canvas/shared.module.css
> fix(): refine tool output

- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.module.css
- mock-task.mjs
> fix(): add basic table style

- bricks/advanced/src/workbench-layout-v2/DraggableComponentMenuItem.module.css
- bricks/advanced/src/workbench-layout-v2/index.tsx
- bricks/advanced/src/workbench-layout-v2/styles.module.css
> chore(): 调整样式

- bricks/ai-portal/src/chat-box/index.tsx
- bricks/ai-portal/src/chat-box/styles.shadow.css
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.module.css
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.tsx
- bricks/ai-portal/src/cruise-canvas/NodeRequirement/NodeRequirement.module.css
- bricks/ai-portal/src/cruise-canvas/PlanProgress/PlanProgress.module.css
> fix(): refine tool detail

- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.tsx
- bricks/advanced/src/workbench-layout-v2/index.tsx
- bricks/advanced/src/workbench-layout-v2/styles.module.css
refs: DESKTOP-508
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): Drag and drop cards to snap

- bricks/ai-portal/docs/chat-history.md
- bricks/ai-portal/src/bootstrap.ts
- bricks/ai-portal/src/chat-history/i18n.ts
- bricks/ai-portal/src/chat-history/index.spec.tsx
- bricks/ai-portal/src/chat-history/index.tsx
- bricks/ai-portal/src/chat-history/styles.shadow.css
- bricks/api-market/src/apis-directory-tree/wrapped-bricks.ts
- bricks/presentational/src/card-item/index.tsx
- package.json
- yarn.lock
> feat(): new brick: chat-history

- bricks/advanced/package.json
- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.tsx
- bricks/advanced/src/workbench-layout-v2/index.tsx
- bricks/advanced/src/workbench-layout-v2/styles.module.css
- yarn.lock
refs: DESKTOP-486
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support card height adapt

- bricks/vs/src/code-editor/workers/lintYaml.spec.ts
- bricks/vs/src/code-editor/workers/lintYaml.ts
- yarn.lock
> fix(): warn when forgot to quote expression which contains a colon

- bricks/vs/src/code-editor/workers/lintYaml.spec.ts
- bricks/vs/src/code-editor/workers/lintYaml.ts
> fix(): show yaml syntax error

- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.tsx
- bricks/advanced/src/workbench-layout-v2/index.spec.tsx
- bricks/advanced/src/workbench-layout-v2/index.tsx
- bricks/advanced/src/workbench-layout-v2/styles.module.css
refs: DESKTOP-522
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复抖动问题,去除拖拽限制

- bricks/nav/docs/query-search.md
- bricks/nav/package.json
- bricks/nav/src/bootstrap.ts
- bricks/nav/src/query-search/i18n.ts
- bricks/nav/src/query-search/index.spec.tsx
- bricks/nav/src/query-search/index.tsx
- bricks/nav/src/query-search/styles.shadow.css
> feat(): eo-query-search ref CMDB_INSTANCE-2770

- bricks/advanced/src/workbench-layout-v2/index.tsx
refs: CMDB_MODEL-394
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复默认模板渲染宽度变化导致按照 layouts 顺序计算每个卡片的x和 y 坐标导致,有卡片互换

- bricks/advanced/src/workbench-layout-v2/styles.module.css
Closes CMDB_MODEL-399
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 点击设置按钮，点击自定义，点击我的账号，账号数据被保存、取消按钮遮挡了

- bricks/nav/src/query-search/index.spec.tsx
- bricks/nav/src/query-search/index.tsx
- bricks/nav/src/query-search/styles.shadow.css
> fix(): eo-query-search ref CMDB_INSTANCE-2770

- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.module.css
> chore(): change style

- bricks/advanced/src/interfaces/workbench.ts
- bricks/advanced/src/workbench-layout-v2/DraggableComponentMenuItem.module.css
- bricks/advanced/src/workbench-layout-v2/DraggableComponentMenuItem.spec.tsx
- bricks/advanced/src/workbench-layout-v2/DraggableComponentMenuItem.tsx
- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.module.css
- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.spec.tsx
- bricks/advanced/src/workbench-layout-v2/index.spec.tsx
- bricks/advanced/src/workbench-layout-v2/index.tsx
- bricks/advanced/src/workbench-layout-v2/styles.module.css
Closes APM-1721
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 工作台卡片类型支持缩略图

- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.module.css
- bricks/advanced/src/workbench-layout-v2/index.tsx
Closes DESKTOP-554
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 工作台-自定义排行卡片没有自适应高度

- bricks/advanced/src/tree-select/index.tsx
- bricks/advanced/src/tree-select/styles.shadow.css
> fix(): eo-tree-select支持设置popupMatchSelectWidth属性 ref CUSTOMIZE-1128

- bricks/ai-portal/src/cruise-canvas/ToolCallDetail/ToolCallDetail.tsx
- bricks/ai-portal/src/cruise-canvas/ToolCallStatus/ToolCallStatus.module.css
- bricks/ai-portal/src/cruise-canvas/ToolCallStatus/ToolCallStatus.tsx
- bricks/ai-portal/src/cruise-canvas/ToolProgressLine/ToolProgressLine.module.css
- bricks/ai-portal/src/cruise-canvas/ToolProgressLine/ToolProgressLine.tsx
- bricks/ai-portal/src/cruise-canvas/bricks.ts
- bricks/ai-portal/src/cruise-canvas/interfaces.ts
- bricks/ai-portal/src/cruise-canvas/utils/getToolDataProgress.ts
- bricks/ai-portal/src/cruise-canvas/utils/index.spec.ts
- bricks/ai-portal/src/cruise-canvas/utils/index.ts
Closes INFRA-4099
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 智能门户巡航页 - 支持显示任务进度信息

- bricks/ui-test/src/bootstrap.ts
- bricks/ui-test/src/custom-processors/get-tree-data.ts
- bricks/ui-test/src/data-providers/__snapshots__/get-source-code-by-suites.spec.ts.snap
- bricks/ui-test/src/data-providers/__snapshots__/prettier-code.spec.ts.snap
- bricks/ui-test/src/data-providers/export-as-file.ts
- bricks/ui-test/src/data-providers/get-source-code-by-suites.spec.ts
- bricks/ui-test/src/data-providers/get-source-code-by-suites.ts
- bricks/ui-test/src/data-providers/prettier-code.spec.ts
- bricks/ui-test/src/data-providers/prettier-code.ts
- bricks/ui-test/src/interface.ts
- bricks/ui-test/src/utils/parseSuiteAst.ts
Refs NEXT_BUILDER-5376
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): Optimize the logic of parsing the source code

- bricks/ai-portal/package.json
- bricks/ai-portal/src/cruise-canvas/AlertEvents/AlertEvents.module.css
- bricks/ai-portal/src/cruise-canvas/AlertEvents/AlertEvents.tsx
- bricks/ai-portal/src/cruise-canvas/DeploymentChanges/DeploymentChanges.module.css
- bricks/ai-portal/src/cruise-canvas/DeploymentChanges/DeploymentChanges.tsx
- bricks/ai-portal/src/cruise-canvas/TraceList/TraceList.module.css
- bricks/ai-portal/src/cruise-canvas/TraceList/TraceList.tsx
- bricks/ai-portal/src/cruise-canvas/bricks.ts
Closes INFRA-4101
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 智能门户巡航页 - 支持显示告警信息

- bricks/advanced/src/interfaces/workbench.ts
- bricks/advanced/src/workbench-layout-v2/utils.spec.ts
- bricks/advanced/src/workbench-layout-v2/utils.ts
Closes MONITOR-10025
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 工作台卡片更多按钮支持文案配置

- bricks/advanced/src/workbench-layout-v2/utils.ts
Closes DESKTOP-538
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 「资源巡检异常结果」支持more设置

- bricks/presentational/src/card-item/index.tsx
> fix(): eo-card-item支持设置标题样式 ref CMDB_INSTANCE-2850

- bricks/form/src/select/index.tsx
> feat(select): add v2 change event to emit selected values only

- bricks/data-view/docs/china-map.md
- bricks/data-view/src/china-map/index.spec.tsx
- bricks/data-view/src/china-map/index.tsx
> feat(china-map): add support for specific coordinates in data source

- bricks/ui-test/src/data-providers/preview/RecordContext.spec.ts
- bricks/ui-test/src/data-providers/preview/RecordContext.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/basic-bricks.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/forms.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/index.ts
- bricks/ui-test/src/data-providers/preview/interfaces.ts
- bricks/ui-test/src/data-providers/preview/recorder.ts
- bricks/ui-test/src/data-providers/preview/utils.spec.ts
- bricks/ui-test/src/data-providers/preview/utils.ts
> fix(): add custom brick record

- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.module.css
- bricks/ai-portal/src/cruise-canvas/ZoomBar/ZoomBar.tsx
> fix(): fix style

- bricks/nav/src/query-search/index.tsx
> fix(): 全局搜索器默认选项增加工单搜索 ref CMDB_VIEW-466

- bricks/data-view/docs/china-map-chart.md
> docs(): fix a broken link in docs

- bricks/ui-test/src/data-providers/preview/brick-recorder/basic-bricks.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/forms.ts
- bricks/ui-test/src/data-providers/preview/recorder.ts
- bricks/ui-test/src/data-providers/preview/utils.spec.ts
- bricks/ui-test/src/data-providers/preview/utils.ts
> fix(): refine custom brick record

- bricks/ui-test/src/data-providers/preview/brick-recorder/forms.ts
Refs NEXT_BUILDER-5423
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine brick record

- bricks/advanced/src/workbench-layout-v2/index.spec.tsx
- bricks/advanced/src/workbench-layout-v2/index.tsx
Closes ITSERVICE_NEXT-9774
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 将内层实现的border等css配置改到drag-box上，统一模块间的间距

- bricks/diagram/src/draw-canvas/index.spec.tsx
- bricks/diagram/src/draw-canvas/processors/initaliContainerLayout.ts
- bricks/diagram/src/draw-canvas/processors/updateCells.ts
Closes CMDB_VIEW-529
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 架构图构件支持同时动态生成的容器以及节点

- bricks/ai-portal/package.json
- bricks/ai-portal/src/cruise-canvas/ToolCallStatus/ToolCallStatus.tsx
- bricks/ai-portal/src/cruise-canvas/constants.ts
- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/interfaces.ts
- bricks/ai-portal/src/cruise-canvas/styles.module.css
- bricks/ai-portal/src/cruise-canvas/useAutoCenter.spec.ts
- bricks/ai-portal/src/cruise-canvas/useAutoCenter.ts
- bricks/ai-portal/src/cruise-canvas/useTaskGraph.ts
- bricks/ai-portal/src/cruise-canvas/utils/getScrollTo.ts
- bricks/ai-portal/src/cruise-canvas/utils/index.ts
- bricks/diagram/package.json
- bricks/diagram/src/shared/canvas/processors/getCellsRect.ts
- package.json
- shared/diagram/package.json
- shared/diagram/src/index.ts
- shared/diagram/src/mergeRects.spec.ts
- shared/diagram/src/mergeRects.ts
- shared/diagram/test.config.js
- shared/diagram/tsconfig.build.json
- shared/diagram/tsconfig.json
- yarn.lock
> feat(): support scroll to node

- bricks/ui-test/src/utils/parseSuiteAst.spec.ts
- bricks/ui-test/src/utils/parseSuiteAst.ts
> fix(): support code in describe

- bricks/ai-portal/src/cruise-canvas/PlanProgress/PlanProgress.module.css
- bricks/ai-portal/src/cruise-canvas/PlanProgress/PlanProgress.tsx
> fix(): close plan details when click outside

- bricks/ai-portal/deploy-default/package.conf.yaml
> fix(): fix deps

- bricks/ui-test/src/data-providers/preview/brick-recorder/forms.ts
> fix(): add clear action

- bricks/ui-test/src/data-providers/preview/brick-recorder/forms.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/index.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/presentational-bricks.ts
- shared/ui-test/src/data/bricks/presentational-bricks.ts
> fix(): brick custom record

- bricks/ai-portal/deploy-default/package.conf.yaml
- bricks/ai-portal/docs/stat-with-mini-chart.md
- bricks/ai-portal/package.json
- bricks/ai-portal/src/bootstrap.ts
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.tsx
- bricks/ai-portal/src/cruise-canvas/NodeView/NodeView.tsx
- bricks/ai-portal/src/cruise-canvas/ToolCallDetail/ToolCallDetail.tsx
- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertDashboard.ts
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertForm.ts
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertView.ts
- bricks/ai-portal/src/cruise-canvas/utils/converters/expressions.ts
- bricks/ai-portal/src/stat-with-mini-chart/index.spec.tsx
- bricks/ai-portal/src/stat-with-mini-chart/index.tsx
- bricks/ai-portal/src/stat-with-mini-chart/styles.shadow.css
- bricks/mini-chart/src/mini-line-chart/draw.ts
- bricks/mini-chart/src/mini-line-chart/index.tsx
- bricks/presentational/src/descriptions/index.tsx
> fix(): refine dashboard

- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.tsx
- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/interfaces.ts
- bricks/ai-portal/src/cruise-canvas/useTaskGraph.ts
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertView.ts
> fix(): set translate extent

- bricks/ai-portal/deploy-default/package.conf.yaml
- bricks/ai-portal/src/cruise-canvas/NodeView/NodeView.tsx
- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/reducers/jobs.spec.ts
- bricks/ai-portal/src/cruise-canvas/reducers/jobs.ts
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertEvents.ts
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertTable.ts
> fix(): fix zoomer extent, support table pagination

- bricks/ui-test/src/data-providers/preview/brick-recorder/basic-bricks.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/basic-v3.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/container-v3.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/container.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/forms-v3.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/forms.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/index.ts
- bricks/ui-test/src/data-providers/preview/brick-recorder/presentational-bricks.ts
Refs NEXT_BUILDER-5505
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): add brick record action

- bricks/ai-portal/src/cruise-canvas/utils/converters/convertDescriptions.ts
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertTable.ts
- bricks/ai-portal/src/cruise-canvas/utils/converters/findObjectIdByUsedDataContexts.ts
> fix(): handle context deps when finding objectId

- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.module.css
- bricks/ai-portal/src/cruise-canvas/ToolCallDetail/ToolCallDetail.tsx
- bricks/ai-portal/src/cruise-canvas/ToolCallStatus/ToolCallStatus.tsx
> fix(): hide job node heading

- bricks/ai-portal/src/cruise-canvas/CmdbInstanceDetail/CmdbInstanceDetail.tsx
- bricks/ai-portal/src/cruise-canvas/EnhancedMarkdown/EnhancedMarkdown.tsx
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.tsx
- bricks/ai-portal/src/cruise-canvas/shared.module.css
> fix(): refine node size

- bricks/ai-portal/src/cruise-canvas/CodeBlock/CodeBlock.module.css
- bricks/markdown/docs/eo-markdown-display.md
- shared/markdown/package.json
- shared/markdown/src/MarkdownComponent.tsx
- shared/markdown/src/rehypeMermaid.ts
- shared/markdown/src/rehypePrism.ts
- shared/markdown/src/utils.ts
- yarn.lock
> feat(): support mermaid in markdown

- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/useZoom.ts
> fix(): refine manual scroll up detecting

- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/interfaces.ts
- bricks/ai-portal/src/cruise-canvas/useAutoCenter.spec.ts
- bricks/ai-portal/src/cruise-canvas/useAutoCenter.ts
- bricks/ai-portal/src/cruise-canvas/useZoom.ts
- bricks/ai-portal/src/elevo-sidebar/ChatHistory.tsx
> fix(): refine zoom transition

- bricks/ai-portal/src/elevo-sidebar/ChatHistory.tsx
- bricks/ai-portal/src/elevo-sidebar/index.tsx
- bricks/ai-portal/src/elevo-sidebar/styles.shadow.css
> fix(sidebar): show active history task

- bricks/ai-portal/src/chat-history/index.tsx
- bricks/ai-portal/src/cruise-canvas/NodeRequirement/NodeRequirement.module.css
- bricks/ai-portal/src/cruise-canvas/PlanProgress/PlanProgress.tsx
- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/useTaskDetail.ts
- bricks/ai-portal/src/cruise-canvas/utils/handleKeyboardNav.ts
- bricks/ai-portal/src/elevo-sidebar/ChatHistory.tsx
> fix(): refine keyboard nav, fix moment manipulation, separate replay and delay props

- bricks/advanced/src/workbench-layout-v2/index.tsx
- bricks/advanced/src/workbench-layout-v2/utils.ts
refs: CMDB_CONSUME-988
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 支持自定义配置卡片配置

- bricks/ai-portal/src/cruise-canvas/CanvasContext.ts
- bricks/ai-portal/src/cruise-canvas/ChatBox/ChatBox.module.css
- bricks/ai-portal/src/cruise-canvas/ChatBox/ChatBox.tsx
- bricks/ai-portal/src/cruise-canvas/ExpandedView/ExpandedView.tsx
- bricks/ai-portal/src/cruise-canvas/Nav/Nav.tsx
- bricks/ai-portal/src/cruise-canvas/NodeView/NodeView.tsx
- bricks/ai-portal/src/cruise-canvas/ZoomBar/ZoomBar.module.css
- bricks/ai-portal/src/cruise-canvas/i18n.ts
- bricks/ai-portal/src/cruise-canvas/index.tsx
- bricks/ai-portal/src/cruise-canvas/interfaces.ts
- bricks/ai-portal/src/cruise-canvas/useTaskDetail.ts
> feat(): support chat box in canvas

- bricks/ai-portal/src/cruise-canvas/ChatBox/ChatBox.tsx
- bricks/ai-portal/src/cruise-canvas/Nav/Nav.tsx
> fix(): auto scroll to last active nav item

- bricks/diagram/src/draw-canvas/decorators/DecoratorGroup.tsx
- bricks/diagram/src/draw-canvas/index.spec.tsx
- bricks/diagram/src/draw-canvas/processors/handleNodeContainedChange.ts
- bricks/diagram/src/draw-canvas/processors/initialContainerLayout.ts
- bricks/diagram/src/draw-canvas/processors/initialGroupLayout.ts
- bricks/diagram/src/draw-canvas/processors/staggeredLayout.ts
- bricks/diagram/src/draw-canvas/processors/updateCells.ts
- bricks/diagram/src/draw-canvas/reducers/interfaces.ts
- bricks/diagram/src/shared/canvas/styles.shadow.css
Refs CMDB_CONSUME-955
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复页面确认数据后，同时添加容器、分组、节点的场景

- bricks/ui-test/src/data-providers/data/commands/custom.ts
- bricks/ui-test/src/interface.ts
- bricks/ui-test/src/utils/parseSuiteAst.spec.ts
- bricks/ui-test/src/utils/parseSuiteAst.ts
Refs NEXT_BUILDER-5599
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): describe 标题增加小产品id和文件名称信息

- bricks/ai-portal/src/elevo-sidebar/index.tsx
- bricks/ai-portal/src/mcp-tools/styles.shadow.css
> fix(sidebar): increase padding top

- bricks/ai-portal/src/cruise-canvas/CmdbInstanceDetail/CmdbInstanceDetail.tsx
- bricks/ai-portal/src/cruise-canvas/interfaces.ts
- bricks/ai-portal/src/elevo-sidebar/index.tsx
> fix(): compatible with string outputSchema

- bricks/ai-portal/src/cruise-canvas/NodeView/NodeView.tsx
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertDashboard.ts
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertView.ts
> fix(): support dashboard comparison

- bricks/ai-portal/src/cruise-canvas/FilePreview/FilePreview.module.css
- bricks/ai-portal/src/cruise-canvas/FilePreview/FilePreview.tsx
- bricks/ai-portal/src/cruise-canvas/utils/file.ts
> fix(): pdf preview with <embed>

- shared/jsx-storyboard/src/constructors/element.ts
- shared/jsx-storyboard/src/constructors/values.ts
- shared/jsx-storyboard/src/interfaces.ts
- shared/jsx-storyboard/src/parseJsx.spec.ts
- shared/jsx-storyboard/src/utils.ts
> fix(): disallow arrow functions

- shared/jsx-storyboard/src/constructors/element.ts
- shared/jsx-storyboard/src/constructors/values.ts
- shared/jsx-storyboard/src/interfaces.ts
> fix(): add ambiguous props

- bricks/ai-portal/src/elevo-sidebar/styles.shadow.css
> fix(): refine toolbar background

- shared/jsx-storyboard/src/constructors/element.ts
- shared/jsx-storyboard/src/constructors/events.ts
- shared/jsx-storyboard/src/interfaces.ts
- shared/jsx-storyboard/src/parseJsx.ts
> fix(): set ambiguous params for api calls

- bricks/nav/src/launchpad-button-v2/Launchpad.spec.tsx
- bricks/nav/src/launchpad-button-v2/api.spec.ts
- bricks/nav/src/launchpad-button-v2/api.ts
- bricks/nav/src/search-launchpad/index.spec.tsx
Refs NEXT_BUILDER-5427
请勾选以下两组选项其中之一：
或者：
>
>
> fix(launchpad-button-v2): Fix display of application names in directory

- bricks/nav/src/launchpad-button-v2/Launchpad.tsx
- bricks/nav/src/launchpad-button-v2/styles.shadow.css
Closes NEXT_BUILDER-5664
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): launchpad支持三列展示

- bricks/ai-portal/src/chat-stream/useChatStream.ts
- bricks/ai-portal/src/cruise-canvas/Nav/Nav.module.css
- bricks/ai-portal/src/cruise-canvas/NodeJob/NodeJob.tsx
- bricks/ai-portal/src/elevo-sidebar/styles.shadow.css
- bricks/ai-portal/src/mcp-tools/i18n.ts
- bricks/ai-portal/src/mcp-tools/index.tsx
> fix(): distinguish user messages

- bricks/nav/src/launchpad-button-v2/Launchpad.tsx
> chore(): buid again

- bricks/ai-portal/docs/ai-agents.md
- bricks/ai-portal/src/ai-agents/i18n.ts
- bricks/ai-portal/src/ai-agents/index.spec.tsx
- bricks/ai-portal/src/ai-agents/index.tsx
- bricks/ai-portal/src/ai-agents/styles.shadow.css
- bricks/ai-portal/src/bootstrap.ts
> feat(): new brick: ai-agents

- bricks/advanced/src/workbench-layout-v2/index.tsx
> fix(): DESKTOP-597 工作台和dashboard支持设置卡片边距 ref DESKTOP-597

- bricks/ai-portal/src/cruise-canvas/reducers/jobs.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertEvents.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertFormItem.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertJsx.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertText.ts
- bricks/ai-portal/src/shared/CreatedView/CreatedView.tsx
- bricks/ai-portal/src/shared/ExpandedView/ExpandedView.tsx
- bricks/ai-portal/src/shared/JsxEditor/JsxEditor.tsx
- bricks/ui-test/package.json
- bricks/vb-experiment/package.json
- bricks/vs/package.json
- yarn.lock
> fix(): support converting tsx storyboard

- bricks/presentational/src/card-item/index.tsx
Closes BRICK-598
请勾选以下两组选项其中之一：
或者：
>
>
> feat(card-item): add action.click event

- bricks/ai-portal/build.config.js
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertButton.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertDashboard.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertDescriptions.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertForm.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertList.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertModal.ts
- bricks/ai-portal/src/cruise-canvas/utils/jsx-converters/convertTable.ts
- bricks/ai-portal/src/shared/JsxEditor/JsxEditor.tsx
- bricks/vs/build.config.js
- bricks/vs/src/code-editor/index.tsx
- shared/jsx-storyboard/lib/actions.d.ts
- shared/jsx-storyboard/lib/components.d.ts
- shared/jsx-storyboard/lib/contracts.d.ts
- shared/jsx-storyboard/package.json
- shared/monaco-textmate/src/grammars/brick-next/injection-quoted-double.json
- shared/monaco-textmate/src/grammars/brick-next/injection-quoted-single.json
- shared/monaco-textmate/src/grammars/brick-next/injection-unquoted.json
- shared/monaco-textmate/themes/dark-modern.json
- shared/monaco-textmate/themes/light-modern.json
> fix(): add libs for jsx editor

- bricks/ai-portal/src/cruise-canvas/useConversationGraph.ts
> fix(): add loading nodes

- bricks/visual-builder/src/bootstrap.ts
- bricks/visual-builder/src/data-providers/get-usage-member-statistics.spec.ts
- bricks/visual-builder/src/data-providers/get-usage-member-statistics.ts
Refs NEXT_BUILDER-5670
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support new provider

- bricks/ai-portal/package.json
- bricks/ai-portal/src/cruise-canvas/utils/converters/convertView.ts
- bricks/ai-portal/src/elevo-sidebar/LegacyChatHistory.tsx
- bricks/ai-portal/src/elevo-sidebar/index.tsx
- bricks/ai-portal/src/shared/CreatedView/CreatedView.tsx
- bricks/ai-portal/src/shared/ExpandedView/ExpandedView.tsx
- bricks/vs/package.json
- shared/jsx-storyboard/src/converters/convertJsx.ts
- shared/jsx-storyboard/src/index.ts
- shared/jsx-storyboard/src/interfaces.ts
- yarn.lock
> fix(): conversation history

- bricks/presentational/docs/eo-card-item.md
- bricks/presentational/src/card-item/index.tsx
- bricks/presentational/src/card-item/styles.shadow.css
> Williamcai/bricks/presentational/card item/adjust style of colored border

- bricks/ai-portal/src/cruise-canvas/LegacyCruiseCanvas.tsx
- bricks/ai-portal/src/cruise-canvas/NodeEnd/NodeEnd.tsx
- bricks/ai-portal/src/cruise-canvas/useConversationGraph.ts
- bricks/ai-portal/src/elevo-sidebar/ChatHistory.tsx
- bricks/ai-portal/src/elevo-sidebar/i18n.ts
- bricks/ai-portal/src/elevo-sidebar/index.tsx
- bricks/ai-portal/src/elevo-sidebar/styles.shadow.css
> feat(): show projects in sidebar

- bricks/form-platform/src/user-or-user-group-select/index.spec.tsx
- bricks/form-platform/src/user-or-user-group-select/index.tsx
> fix(): fix user/group select options

- bricks/advanced/src/workbench-layout-v2/DroppableComponentLayoutItem.tsx
> fix(): CMDB_MODEL-501 dashboard的边框宽度设置为20，编辑按钮看不见了  ref CMDB_MODEL-501

- bricks/ai-portal/src/page-container/index.tsx
- bricks/ai-portal/src/page-container/styles.shadow.css
> fix(page-container): add toolbar slot

- bricks/ai-portal/src/chat-stream/index.tsx
> fix(): fix replay watch again

- bricks/ai-portal/src/chat-stream/ChatStream.tsx
- bricks/ai-portal/src/chat-stream/LegacyChatStream.tsx
- bricks/ai-portal/src/chat-stream/index.tsx
- bricks/ai-portal/src/chat-stream/useConversationStream.ts
- bricks/ai-portal/src/chat-stream/useTaskStream.ts
- bricks/ai-portal/src/cruise-canvas/CruiseCanvas.tsx
- bricks/ai-portal/src/cruise-canvas/useConversationDetail.ts
> feat(): new chat stream

- bricks/ui-test/package.json
- bricks/ui-test/src/data-providers/apply-snippet.spec.ts
- bricks/ui-test/src/data-providers/apply-snippet.ts
- bricks/ui-test/src/data-providers/clone-nodes.spec.ts
- bricks/ui-test/src/data-providers/clone-nodes.ts
- bricks/ui-test/src/data-providers/insert-node.spec.ts
- bricks/ui-test/src/data-providers/insert-node.ts
- bricks/ui-test/src/data-providers/save-recorded-commands.spec.ts
- bricks/ui-test/src/data-providers/save-recorded-commands.ts
- bricks/ui-test/src/data-providers/shared/createNodes.spec.ts
- bricks/ui-test/src/data-providers/shared/createNodes.ts
- yarn.lock
Refs NEXT_BUILDER-5710
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 调整测试用例接口为业务接口，以便在review 看到相关记录变更

- bricks/ai-portal/src/elevo-sidebar/ChatHistory.tsx
- bricks/ai-portal/src/elevo-sidebar/index.tsx
> fix(): fix chat history

- bricks/ai-portal/src/chat-box/index.tsx
- bricks/ai-portal/src/chat-box/styles.shadow.css
Refs NEXT_BUILDER-5729
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support actions slot

- bricks/ai-portal/src/chat-stream/ChatStream.tsx
- bricks/ai-portal/src/cruise-canvas/CruiseCanvas.tsx
- bricks/ai-portal/src/shared/interfaces.ts
> fix(): fix show feedback after failed

- bricks/form-platform/src/user-or-user-group-select/index.spec.tsx
- bricks/form-platform/src/user-or-user-group-select/index.tsx
Removed prop mergeUseAndUserGroup, now always use merged values.
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix eo-user-or-user-group-select

- bricks/ai-portal/src/cruise-canvas/ToolCallStatus/ToolCallStatus.module.css
- bricks/ai-portal/src/cruise-canvas/ToolCallStatus/ToolCallStatus.tsx
> fix(): show job timing

- bricks/ai-portal/docs/action-buttons.md
- bricks/ai-portal/src/action-buttons/index.tsx
- bricks/ai-portal/src/dropdown-select/index.tsx
- bricks/ai-portal/src/goal-card-list/CardItem/CardItem.shadow.css
- bricks/ai-portal/src/goal-card-list/CardItem/CardItem.spec.tsx
- bricks/ai-portal/src/goal-card-list/CardItem/CardItem.tsx
> fix(): Some optimizations

- bricks/ai-portal/src/chat-box/index.spec.tsx
- bricks/ai-portal/src/chat-box/index.tsx
- bricks/ai-portal/src/goal-card-list/CardItem/CardItem.shadow.css
- bricks/ai-portal/src/goal-card-list/CardItem/CardItem.tsx
- bricks/ai-portal/src/goal-card-list/i18n.ts
- bricks/ai-portal/src/goal-card-list/index.tsx
Refs NEXT_BUILDER-5771
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): interactional modification

- bricks/ai-portal/src/goal-card-list/index.spec.tsx
- bricks/ai-portal/src/goal-card-list/index.tsx
- bricks/ai-portal/src/goal-card-list/styles.shadow.css
> fix(): add loading status

- bricks/ai-portal/deploy-default/package.conf.yaml
- bricks/ai-portal/src/activity-timeline/__snapshots__/index.spec.tsx.snap
- bricks/ai-portal/src/activity-timeline/i18n.ts
- bricks/ai-portal/src/activity-timeline/index.spec.tsx
- bricks/ai-portal/src/activity-timeline/index.tsx
- bricks/ai-portal/src/activity-timeline/interfaces.ts
- bricks/ai-portal/src/activity-timeline/styles.shadow.css
- bricks/ai-portal/src/chat-box/index.tsx
- bricks/ai-portal/src/chat-input/index.tsx
- bricks/ai-portal/src/chat-stream/AssistantMessage/AssistantMessage.module.css
- bricks/ai-portal/src/chat-stream/AssistantMessage/AssistantMessage.tsx
> fix(): delegate focus

- bricks/ai-portal/deploy-default/package.conf.yaml
- bricks/ai-portal/src/chat-stream/ChatStream.tsx
- bricks/ai-portal/src/chat-stream/NodeView/NodeView.module.css
- bricks/ai-portal/src/chat-stream/index.tsx
- bricks/ai-portal/src/cruise-canvas/NodeReplay/NodeReplay.module.css
- bricks/ai-portal/src/show-case/index.tsx
> fix(): refine replay in chat ui

- shared/tsx-parser/src/parseSolid.spec.ts
- shared/tsx-parser/src/tsx-constructors/values.ts
> fix(): remove ts as expressions

- shared/tsx-converter/lib/actions.d.ts
- shared/tsx-converter/lib/components.d.ts
- shared/tsx-converter/src/convertComponent.ts
- shared/tsx-converter/src/convertDescriptions.ts
- shared/tsx-converter/src/convertEvents.ts
- shared/tsx-converter/src/convertTable.ts
- shared/tsx-converter/src/convertTemplates.ts
- shared/tsx-converter/src/convertTsx.ts
- shared/tsx-parser/src/interfaces.ts
- shared/tsx-parser/src/parseTsx.ts
- shared/tsx-parser/src/solid/functionComponent.ts
- shared/tsx-parser/src/tsx-constructors/element.ts
- shared/tsx-parser/src/tsx-constructors/events.ts
> feat(): support useRef

- bricks/ai-portal/src/cruise-canvas/FilePreview/FilePreview.tsx
> fix(): fix pdf preview
